eureka:
  client:
    register-with-eureka: false

server:
  port: 8085

spring:

  application:
    name: mimicroservice-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: libro
          uri: http://localhost:8091
          predicates:
            - Path=/api/libro/**
        - id: autor
          uri: http://localhost:8090
          predicates:
            - Path=/api/autor/**
